### PR TITLE
Password import mcf

### PR DESCRIPTION
**Pull request by nikone**
PR for task https://github.com/stormpath/stormpath-sdk-ruby/issues/79

### CODE REVIEW

**Comment by nikone** [comment]
Password import MCF

this feature consists on changing the parameters on directory.create method. So the only thing needed for this feature was to cover it with test and check if everything works.

**Comment by ecrisostomo** [comment]
Looks good, but I think that we should have better docs for the user for this feature. This is because if a user asks how to do this in Ruby we would not be able to point them to any documentation, and we would need to dig deep into the code to figure out/remember how it works.

Should probably add it to the Readme.md in the mean time.

**Comment by nikone** [comment]
I added the description of the feature in Readme and a link to original documentation

**Comment by ecrisostomo** [comment]
Looks good to merge.

**Pull request merged**
