### PR TITLE
Login attempt with organization namekey

### PR DESCRIPTION
**Pull request by DamirSvrtan**
@omgitstom submitted the issue #107 . Before I could document it, I had to enable the feature in the Ruby SDK.

@ecrisostomo please review.

### CODE REVIEW

**Comment by DamirSvrtan** [comment]
@omgitstom I've added documentation as requested in #107

**Comment by ecrisostomo** [comment]
Looks good to merge!

**Comment by ecrisostomo** [comment]
Please add the changes to the changelog before releasing.

**Comment by DamirSvrtan** [comment]
Will do, merging in!

**Pull request merged**
